// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SAVE_ACCESS_TOKEN = 'SAVE_ACCESS_TOKEN'
// Auth

// Bill
export const GET_BILL_SUCCESS = 'GET_BILL_SUCCESS'
export const SAVE_BILL_SUCCESS = 'SAVE_BILL_SUCCESS'
export const CLEAR_BILLS_SUCCESS = 'CLEAR_BILLS_SUCCESS'

//Bill form
export const INITIALIZE_BILL_FORM = 'INITIALIZE_BILL_FORM'
export const UPDATE_BILL_FORM = 'UPDATE_BILL_FORM'

//Filters
export const UPDATE_BILL_FILTERS = 'UPDATE_BILL_FILTERS'